import React from 'react';

const TradingSignals = () => {
  const mockSignals = [
    { id: 1, stock: "AAPL", entry: "175.50", stopLoss: "170.00", target: "185.00", type: "BUY", date: "2026-03-12" },
    { id: 2, stock: "TSLA", entry: "210.20", stopLoss: "220.00", target: "190.00", type: "SELL", date: "2026-03-12" },
    { id: 3, stock: "MSFT", entry: "410.00", stopLoss: "405.00", target: "425.00", type: "BUY", date: "2026-03-11" },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex-grow w-full">
      <div className="flex justify-between items-center mb-10">
        <div>
          <h1 className="text-3xl font-bold text-brand-text">Active Trading Signals</h1>
          <p className="text-brand-muted mt-2">Live, highly accurate signals generated by our expert team.</p>
        </div>
        <div className="bg-brand-dark px-4 py-2 rounded-lg border border-brand-accent/30 text-brand-accent font-semibold animate-pulse">
          Live Market Open
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full bg-brand-nav rounded-xl overflow-hidden shadow-xl border border-brand-accent/20">
          <thead className="bg-brand-dark border-b border-brand-accent/20">
            <tr>
              <th className="px-6 py-4 text-left text-xs font-semibold text-brand-muted uppercase tracking-wider">Date</th>
              <th className="px-6 py-4 text-left text-xs font-semibold text-brand-muted uppercase tracking-wider">Asset</th>
              <th className="px-6 py-4 text-left text-xs font-semibold text-brand-muted uppercase tracking-wider">Type</th>
              <th className="px-6 py-4 text-left text-xs font-semibold text-brand-muted uppercase tracking-wider">Entry</th>
              <th className="px-6 py-4 text-left text-xs font-semibold text-brand-muted uppercase tracking-wider">Target</th>
              <th className="px-6 py-4 text-left text-xs font-semibold text-brand-muted uppercase tracking-wider">Stop Loss</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-brand-accent/10">
            {mockSignals.map(signal => (
              <tr key={signal.id} className="hover:bg-brand-dark/50 transition-smooth">
                <td className="px-6 py-4 whitespace-nowrap text-sm text-brand-muted">{signal.date}</td>
                <td className="px-6 py-4 whitespace-nowrap font-bold text-brand-text">{signal.stock}</td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className={`px-3 py-1 rounded-full text-xs font-bold ${signal.type === 'BUY' ? 'bg-brand-accent/20 text-brand-accent' : 'bg-red-500/20 text-red-500'}`}>
                    {signal.type}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-brand-text">${signal.entry}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-brand-primary font-bold">${signal.target}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-red-400 max-w-xs truncate">${signal.stopLoss}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-12 bg-gradient-to-r from-brand-nav to-brand-dark p-8 rounded-2xl border border-[#0088cc]/30 text-center glow-effect">
        <h3 className="text-xl font-bold text-white mb-2">Want Instant Notifications?</h3>
        <p className="text-brand-muted mb-6">Never miss an entry. Get these signals straight to your phone as soon as they are triggered.</p>
        <a href="https://t.me/telegram" target="_blank" rel="noopener noreferrer" className="bg-[#0088cc] hover:bg-[#0077b5] text-white px-6 py-3 rounded-lg font-bold transition-smooth inline-flex items-center space-x-2">
          <span>Join Telegram Channel</span>
          <span>↗</span>
        </a>
      </div>
    </div>
  );
};

export default TradingSignals;
